import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import WeatherApi from './api/weatherAPI'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input type="text" placeholder="Enter city name"></input>
				<button>Search</button>
				<WeatherApi />
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
